spring.datasource.url=jdbc:mysql://localhost:3306/tshirt_store?useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Kalash151206
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true